# Generated by Django 6.0.1 on 2026-02-10 16:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0011_movie_keywords_en_movie_keywords_uz'),
        ('users', '0003_profile_is_premium_profile_premium_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserMovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, "Hozirda ko'ryapman"), (2, "Ko'rib tugallangan"), (3, "Ko'rish rejamda bor"), (4, "Ko'rish to'xtatilgan"), (5, 'Menga qiziq emas')])),
                ('current_episode', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drama.movie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_list', to='users.profile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('profile', 'movie')},
            },
        ),
    ]
