# Generated by Django 6.0.1 on 2026-03-10 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_xp_usermovielist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Balans (Point)'),
        ),
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_uzs', models.PositiveIntegerField(verbose_name="To'lov summasi (UZS)")),
                ('points', models.PositiveIntegerField(blank=True, verbose_name='Beriladigan Pointlar')),
                ('receipt_image', models.ImageField(upload_to='receipts/%Y/%m/', verbose_name="To'lov cheki")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=15, verbose_name='Holati')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Admin izohi (rad etilsa)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Hisob to'ldirish so'rovi",
                'verbose_name_plural': "Hisob to'ldirish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
