# Generated by Django 6.0.1 on 2026-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_balance_topuprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuprequest',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Beriladigan Pointlar'),
        ),
    ]
