# Generated by Django 6.0.1 on 2026-06-22 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0018_populate_seasons'),
        ('users', '0009_cryptotopuprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_seconds', models.PositiveIntegerField(default=0, verbose_name='Pozitsiya (sekund)')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Davomiyligi (sekund)')),
                ('completed', models.BooleanField(default=False, verbose_name="Ko'rib tugatilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='drama.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ko'rish progressi",
                'verbose_name_plural': "Ko'rish progresslari",
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='users_watch_user_id_6e46fb_idx')],
                'unique_together': {('user', 'episode')},
            },
        ),
    ]
