# Generated by Django 6.0.1 on 2026-06-23 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_watch_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balans (Point)'),
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Miqdor (+kredit / -debet)')),
                ('type', models.CharField(choices=[('opening', "Boshlang'ich balans"), ('topup', "Hisob to'ldirish"), ('crypto_topup', "Kripto to'ldirish"), ('gift', "Aktyorga sovg'a"), ('funding', 'Crowdfunding hissa'), ('vip', 'VIP obuna'), ('refund', 'Qaytarish'), ('adjustment', 'Admin tuzatishi')], max_length=20, verbose_name='Turi')),
                ('balance_after', models.IntegerField(verbose_name='Yozuvdan keyingi balans')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='Manba (model:id)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='users.profile')),
            ],
            options={
                'verbose_name': 'Coin tranzaksiyasi',
                'verbose_name_plural': 'Coin tranzaksiyalari',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['profile', '-created_at'], name='users_coint_profile_314e7e_idx')],
            },
        ),
    ]
