# Generated by Django 6.0.1 on 2026-07-05 13:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_opening_balances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptotopuprequest',
            name='receipt_image',
            field=models.ImageField(upload_to=core.validators.RandomFileName('crypto_receipts'), validators=[core.validators.ImageFileValidator(max_mb=10)], verbose_name="To'lov skrinshotı"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to=core.validators.RandomFileName('profile_pics'), validators=[core.validators.ImageFileValidator(max_mb=5)]),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='receipt_image',
            field=models.ImageField(upload_to=core.validators.RandomFileName('receipts'), validators=[core.validators.ImageFileValidator(max_mb=10)], verbose_name="To'lov cheki"),
        ),
    ]
