# Generated by Django 6.0.1 on 2026-07-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_cryptotopuprequest_receipt_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('price_coins', models.PositiveIntegerField(verbose_name='Narxi (Coin)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Davomiyligi (kun)')),
                ('perks', models.TextField(blank=True, verbose_name='Imtiyozlar (har qatorda bittadan)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sotuvda')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obuna rejasi',
                'verbose_name_plural': 'Obuna rejalari',
                'ordering': ['sort_order', 'price_coins'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('expired', 'Muddati tugagan'), ('canceled', 'Bekor qilingan')], default='active', max_length=10, verbose_name='Holati')),
                ('start_at', models.DateTimeField(verbose_name='Boshlanishi')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugashi')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Avto-uzaytirish (balansdan)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.profile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='users.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'end_at'], name='users_subsc_status_7b4d38_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('profile',), name='unique_active_subscription_per_profile')],
            },
        ),
    ]
