# Generated by Django 6.0.1 on 2026-07-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_seed_default_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='type',
            field=models.CharField(choices=[('opening', "Boshlang'ich balans"), ('topup', "Hisob to'ldirish"), ('crypto_topup', "Kripto to'ldirish"), ('payme', "Payme to'lovi"), ('click', "Click to'lovi"), ('gift', "Aktyorga sovg'a"), ('funding', 'Crowdfunding hissa'), ('vip', 'VIP obuna'), ('refund', 'Qaytarish'), ('adjustment', 'Admin tuzatishi')], max_length=20, verbose_name='Turi'),
        ),
    ]
