# Generated by Django 6.0.1 on 2026-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('system', 'Tizim'), ('topup', "Hisob to'ldirildi"), ('follow', 'Yangi obunachi'), ('subscription', 'Obuna'), ('new_episode', 'Yangi qism'), ('reply', 'Izohga javob'), ('funding', 'Crowdfunding')], default='system', max_length=20, verbose_name='Turi'),
        ),
    ]
