# Generated by Django 6.0.7 on 2026-07-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_p7_t4_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_new_episode',
            field=models.BooleanField(default=True, verbose_name='Yangi qism chiqqanda xabar berish (saytda)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_new_episode_telegram',
            field=models.BooleanField(default=True, verbose_name='Yangi qism chiqqanda xabar berish (Telegram)'),
        ),
    ]
