# Generated by Django 6.0.1 on 2026-07-06 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=10, verbose_name='Provider')),
                ('amount_uzs', models.PositiveIntegerField(verbose_name='Summa (UZS)')),
                ('coins', models.PositiveIntegerField(verbose_name='Beriladigan Coin')),
                ('status', models.CharField(choices=[('created', 'Yaratilgan'), ('paid', "To'langan"), ('canceled', 'Bekor qilingan')], default='created', max_length=10, verbose_name='Holat')),
                ('provider_txn_id', models.CharField(blank=True, max_length=64, verbose_name='Provider tranzaksiya ID')),
                ('provider_state', models.IntegerField(blank=True, null=True, verbose_name='Provider holati')),
                ('cancel_reason', models.IntegerField(blank=True, null=True, verbose_name='Bekor sababi (Payme kodi)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratildi')),
                ('provider_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Provider tranzaksiya vaqti')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'landi")),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilindi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'lov buyurtmasi",
                'verbose_name_plural': "To'lov buyurtmalari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'provider_txn_id'], name='billing_ord_provide_95275a_idx'), models.Index(fields=['user', '-created_at'], name='billing_ord_user_id_5afccd_idx')],
            },
        ),
    ]
