# Generated by Django 6.0.1 on 2026-01-30 23:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="To'liq ismi", max_length=150, verbose_name='Ism Familiya')),
                ('name_uz', models.CharField(help_text="To'liq ismi", max_length=150, null=True, verbose_name='Ism Familiya')),
                ('name_en', models.CharField(help_text="To'liq ismi", max_length=150, null=True, verbose_name='Ism Familiya')),
                ('original_name', models.CharField(blank=True, help_text='Masalan: Lee Min-ho', max_length=150, verbose_name='Asl ismi (Native)')),
                ('description', models.TextField(blank=True, verbose_name='Biografiya')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Biografiya')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Biografiya')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Rasmi')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name="Tug'ilgan sanasi")),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name="Tug'ilgan joyi")),
                ('birth_place_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name="Tug'ilgan joyi")),
                ('birth_place_en', models.CharField(blank=True, max_length=100, null=True, verbose_name="Tug'ilgan joyi")),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=10, verbose_name='Jinsi')),
            ],
            options={
                'verbose_name': 'Aktyor/Rejissor',
                'verbose_name_plural': 'Aktyorlar va Rejissorlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kategoriya nomi')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='Kategoriya nomi')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Janr nomi')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Janr nomi')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Janr nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Qiymat')),
            ],
            options={
                'verbose_name': 'Yulduzcha',
                'verbose_name_plural': 'Yulduzchalar',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='TopSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Slayder nomi')),
                ('rank', models.CharField(help_text='Rasm ustida chiqadigan yozuv', max_length=50, verbose_name='Rank matni')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Slayder rasmi')),
                ('target_url', models.URLField(blank=True, verbose_name="Yo'naltiriluvchi URL")),
            ],
            options={
                'verbose_name': 'Top Slayder',
                'verbose_name_plural': 'Top Slayderlar',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Film nomi (Qidiruv uchun)')),
                ('title_uz', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Film nomi (Qidiruv uchun)')),
                ('title_en', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Film nomi (Qidiruv uchun)')),
                ('original_title', models.CharField(blank=True, max_length=255, verbose_name='Original nomi (Kdrama)')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Slogan')),
                ('tagline_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan')),
                ('tagline_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('description_uz', models.TextField(null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(null=True, verbose_name='Tavsif')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='Poster')),
                ('keywords', models.CharField(default='drama, kdrama', help_text='Vergul bilan ajrating', max_length=255, verbose_name='Meta Keywords')),
                ('year', models.PositiveSmallIntegerField(default=2024, verbose_name='Yili')),
                ('country', models.CharField(max_length=50, verbose_name='Davlat')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Davomiyligi (daqiqada)')),
                ('episodes_count', models.PositiveIntegerField(default=16, verbose_name='Qismlar soni')),
                ('age_limit', models.PositiveIntegerField(default=18, verbose_name='Yosh chegarasi')),
                ('film_embed_code', models.TextField(blank=True, default='<div>...</div>', verbose_name='Film HTML kodi')),
                ('trailer_embed_code', models.TextField(blank=True, verbose_name='Trailer HTML kodi')),
                ('site_rank', models.IntegerField(default=0, verbose_name='Sayt reytingi (Ichki)')),
                ('mdl_rank', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='MyDramaList Reytingi')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('is_draft', models.BooleanField(default=False, verbose_name='Qoralama (Draft)')),
                ('actors', models.ManyToManyField(related_name='acted_movies', to='drama.actor', verbose_name='Aktyorlar')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='drama.category', verbose_name='Kategoriya')),
                ('directors', models.ManyToManyField(related_name='directed_movies', to='drama.actor', verbose_name='Rejissorlar')),
                ('genres', models.ManyToManyField(to='drama.genre', verbose_name='Janrlar')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=100, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Rasm')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='drama.movie', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'Kadr',
                'verbose_name_plural': 'Kadrlar',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Manzil')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='drama.movie', verbose_name='Film')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drama.ratingstar', verbose_name='Yulduz')),
            ],
            options={
                'verbose_name': 'Reyting',
                'verbose_name_plural': 'Reytinglar',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('text', models.TextField(max_length=5000, verbose_name='Izoh matni')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='drama.movie', verbose_name='Film')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='drama.review', verbose_name='Javob berilgan izoh')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
