# Generated by Django 6.0.1 on 2026-02-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
