# Generated by Django 6.0.1 on 2026-02-03 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0002_movie_is_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('title', models.CharField(help_text='Masalan: 1-qism yoki Maxsus qism', max_length=150, verbose_name='Qism nomi')),
                ('episode_number', models.PositiveIntegerField(verbose_name='Qism raqami')),
                ('video_embed_code', models.TextField(help_text='Ushbu qismning video kodi', verbose_name='Video HTML kodi (Embed)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episodes/', verbose_name='Qism uchun rasm')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='drama.movie', verbose_name='Film/Serial')),
            ],
            options={
                'verbose_name': 'Qism',
                'verbose_name_plural': 'Qismlar',
                'ordering': ['episode_number'],
            },
        ),
    ]
