# Generated by Django 6.0.1 on 2026-02-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0003_episode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Aktyor/Aktrisa', 'verbose_name_plural': 'Aktyorlar va Aktrissalar'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(max_length=160, null=True, verbose_name='URL Manzili'),
        ),
        migrations.AddField(
            model_name='movie',
            name='main_actors',
            field=models.ManyToManyField(related_name='main_acted_movies', to='drama.actor', verbose_name='Bosh ro`llarda'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Ism Familiya'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Ism Familiya'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Ism Familiya'),
        ),
    ]
