# Generated by Django 6.0.1 on 2026-02-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0004_alter_actor_options_remove_movie_directors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default='vaqtincha', max_length=160, unique=True, verbose_name='URL Manzili'),
            preserve_default=False,
        ),
    ]
