# Generated by Django 6.0.1 on 2026-02-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0005_alter_actor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topslider',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Slayder nomi'),
        ),
    ]
