# Generated by Django 6.0.1 on 2026-02-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0006_alter_topslider_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
