# Generated by Django 6.0.1 on 2026-02-08 21:54

import drama.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=drama.models.movie_poster_path),
        ),
    ]
