# Generated by Django 6.0.1 on 2026-02-09 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0009_alter_movie_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movieshots',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topslider',
            options={},
        ),
        migrations.AlterField(
            model_name='actor',
            name='original_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Asl ismi (Native)'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='drama.movie'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Qism nomi'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_embed_code',
            field=models.TextField(verbose_name='Video HTML kodi (Embed)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='acted_movies', to='drama.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='drama.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='drama.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_actors',
            field=models.ManyToManyField(related_name='main_acted_movies', to='drama.actor'),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='drama.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='drama.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drama.ratingstar'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='drama.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='drama.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topslider',
            name='rank',
            field=models.CharField(max_length=50, verbose_name='Rank matni'),
        ),
    ]
