# Generated by Django 6.0.1 on 2026-02-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0010_alter_actor_options_alter_episode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='keywords_en',
            field=models.CharField(default='drama, kdrama', help_text='Vergul bilan ajrating', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords_uz',
            field=models.CharField(default='drama, kdrama', help_text='Vergul bilan ajrating', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
    ]
