# Generated by Django 6.0.1 on 2026-02-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0011_movie_keywords_en_movie_keywords_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Teg nomi')),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Kino', 'verbose_name_plural': 'Kinolar'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='keywords_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='keywords_uz',
        ),
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movies', to='drama.tag'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags_en',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='drama.tag'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags_uz',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='drama.tag'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug'], name='drama_movie_slug_8b681b_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['year'], name='drama_movie_year_783974_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['created_at'], name='drama_movie_created_8dfd9a_idx'),
        ),
    ]
