# Generated by Django 6.0.1 on 2026-03-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0012_tag_alter_movie_options_remove_movie_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='total_gifts',
            field=models.PositiveIntegerField(default=0, verbose_name="Umumiy sovg'alar (Coin)"),
        ),
    ]
