# Generated by Django 6.0.1 on 2026-03-12 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0013_actor_total_gifts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_type', models.CharField(choices=[('rose', 'Gul 🌹'), ('coffee', 'Qahva ☕'), ('crown', 'Toj 👑')], max_length=20, verbose_name="Sovg'a turi")),
                ('price', models.PositiveIntegerField(verbose_name='Narxi (Coin)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to='drama.actor', verbose_name='Aktyor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Aktyorga Sovg'a",
                'verbose_name_plural': "Aktyorlarga Sovg'alar",
                'ordering': ['-created_at'],
            },
        ),
    ]
