# Generated by Django 6.0.1 on 2026-06-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0015_fix_indexes_and_episode_constraint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movie',
            new_name='drama_movie_is_draf_2d5431_idx',
            old_name='drama_movie_is_draf_idx',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='drama_movie_is_draf_cc4f47_idx',
            old_name='drama_movie_is_draf_ct_idx',
        ),
        migrations.AddField(
            model_name='episode',
            name='bunny_video_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bunny Stream Video ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='bunny_trailer_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bunny Stream Video ID (Trailer)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='bunny_video_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bunny Stream Video ID (Film)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_embed_code',
            field=models.TextField(blank=True, verbose_name='Video HTML kodi (Eski / Embed)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_embed_code',
            field=models.TextField(blank=True, default='<div>...</div>', verbose_name='Film HTML kodi (Eski)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_embed_code',
            field=models.TextField(blank=True, verbose_name='Trailer HTML kodi (Eski)'),
        ),
    ]
