# Generated by Django 6.0.1 on 2026-06-22 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0016_sync_model_drift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Fasl raqami')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Fasl nomi')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yili')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='drama.movie')),
            ],
            options={
                'verbose_name': 'Fasl',
                'verbose_name_plural': 'Fasllar',
                'ordering': ['number'],
                'unique_together': {('movie', 'number')},
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='drama.season'),
        ),
    ]
