# Generated by Django 6.0.1 on 2026-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0018_populate_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
