# Generated by Django 6.0.1 on 2026-06-24 08:15

from django.db import migrations, models


def migrate_is_draft_to_status(apps, schema_editor):
    """is_draft (bool) -> status (enum), forward."""
    Movie = apps.get_model("drama", "Movie")
    Movie.objects.filter(is_draft=True).update(status="draft")
    Movie.objects.filter(is_draft=False).update(status="published")


def migrate_status_to_is_draft(apps, schema_editor):
    """status (enum) -> is_draft (bool), reverse.

    published -> is_draft=False; draft va scheduled (hali public emas) -> is_draft=True.
    """
    Movie = apps.get_model("drama", "Movie")
    Movie.objects.filter(status="published").update(is_draft=False)
    Movie.objects.exclude(status="published").update(is_draft=True)


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0020_backfill_movie_ratings'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='drama_movie_is_draf_2d5431_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='drama_movie_is_draf_cc4f47_idx',
        ),
        migrations.AddField(
            model_name='movie',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text="'Rejalashtirilgan' bo'lsa: shu vaqtda avtomatik chop etiladi.", null=True, verbose_name='Chop etish vaqti'),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('scheduled', 'Rejalashtirilgan'), ('published', 'Chop etilgan')], default='published', max_length=10, verbose_name='Holat'),
        ),
        # is_draft -> status ko'chirish (RemoveField is_draft'dan OLDIN — ma'lumot saqlanadi)
        migrations.RunPython(migrate_is_draft_to_status, migrate_status_to_is_draft),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status', '-created_at'], name='drama_movie_status_7cc485_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status', 'publish_at'], name='drama_movie_status_98179c_idx'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'scheduled'), _negated=True), ('publish_at__isnull', False), _connector='OR'), name='movie_scheduled_requires_publish_at'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_draft',
        ),
    ]
