# Generated by Django 6.0.1 on 2026-06-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0021_remove_movie_drama_movie_is_draf_2d5431_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='upload_status',
            field=models.CharField(choices=[('none', "Yo'q"), ('uploading', 'Yuklanmoqda'), ('processing', 'Qayta ishlanmoqda (encoding)'), ('ready', 'Tayyor'), ('failed', 'Xato')], default='none', max_length=12, verbose_name='Yuklash holati'),
        ),
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='episode_uploads/', verbose_name="Video fayl (Bunny'ga avtomatik yuklanadi)"),
        ),
    ]
