# Generated by Django 6.0.1 on 2026-06-24 17:44

from django.db import migrations


def merge_tags_into_base(apps, schema_editor):
    """tags_uz UNION tags_en -> asl tags (forward). Hech qanday bog'lanish yo'qolmaydi."""
    Movie = apps.get_model("drama", "Movie")
    for movie in Movie.objects.all():
        combined = set(movie.tags_uz.all()) | set(movie.tags_en.all())
        if combined:
            movie.tags.set(combined)


def split_tags_to_uz(apps, schema_editor):
    """asl tags -> tags_uz (reverse)."""
    Movie = apps.get_model("drama", "Movie")
    for movie in Movie.objects.all():
        movie.tags_uz.set(movie.tags.all())


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0022_episode_upload_status_episode_video_file'),
    ]

    operations = [
        # tags_uz/tags_en bog'lanishlarini asl tags'ga ko'chirish (RemoveField'dan OLDIN)
        migrations.RunPython(merge_tags_into_base, split_tags_to_uz),
        migrations.RemoveField(
            model_name='movie',
            name='tags_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tags_uz',
        ),
    ]
