# Generated by Django 6.0.1 on 2026-07-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0023_remove_movie_tags_en_remove_movie_tags_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_card',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='movies/cards/', verbose_name='Poster (karta, 342px)'),
        ),
    ]
