# Generated by Django 6.0.1 on 2026-07-05 13:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0024_movie_poster_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(upload_to='actors/', validators=[core.validators.ImageFileValidator()], verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='episodes/', validators=[core.validators.ImageFileValidator()], verbose_name='Qism uchun rasm'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='episode_uploads/', validators=[core.validators.VideoFileValidator(max_mb=500)], verbose_name="Video fayl (Bunny'ga avtomatik yuklanadi)"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movies/', validators=[core.validators.ImageFileValidator()], verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='image',
            field=models.ImageField(upload_to='movie_shots/', validators=[core.validators.ImageFileValidator()], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='topslider',
            name='image',
            field=models.ImageField(upload_to='sliders/', validators=[core.validators.ImageFileValidator()], verbose_name='Slayder rasmi'),
        ),
    ]
