# Generated by Django 6.0.1 on 2026-07-05 13:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0025_alter_actor_image_alter_episode_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upload_status',
            field=models.CharField(choices=[('none', "Yo'q"), ('uploading', 'Yuklanmoqda'), ('processing', 'Qayta ishlanmoqda (encoding)'), ('ready', 'Tayyor'), ('failed', 'Xato')], default='none', max_length=12, verbose_name='Yuklash holati'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='movie_uploads/', validators=[core.validators.VideoFileValidator(max_mb=500)], verbose_name="Video fayl (Bunny'ga avtomatik yuklanadi)"),
        ),
    ]
