# Generated by Django 6.0.1 on 2026-07-05 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0026_movie_upload_status_movie_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['country'], name='drama_movie_country_562e26_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['movie', 'parent'], name='drama_revie_movie_i_944416_idx'),
        ),
    ]
