# Generated by Django 6.0.1 on 2026-07-11 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0028_movie_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Yashirilgan (moderatsiya)'),
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam / reklama'), ('abuse', 'Haqorat / xafa qiluvchi'), ('spoiler', 'Belgisiz spoyler'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Sabab')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi (izoh yashirildi)'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='drama.review')),
            ],
            options={
                'verbose_name': 'Izoh shikoyati',
                'verbose_name_plural': 'Izoh shikoyatlari (moderatsiya)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='drama_revie_status_d58120_idx')],
                'constraints': [models.UniqueConstraint(fields=('review', 'reporter'), name='review_report_once')],
            },
        ),
    ]
