# Generated by Django 6.0.7 on 2026-07-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0029_p14_t3_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='followers_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Obunachilarga xabar berilgan'),
        ),
    ]
