# Generated by Django 6.0.7 on 2026-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0030_v2a_t1_new_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='TMDB ID'),
        ),
    ]
