# Generated by Django 6.0.7 on 2026-07-12 13:54
#
# + backfill: MAVJUD kategoriyalar -> "reels". Shu kungacha barcha kontent
# reels pleyerida ochilardi — deploy'da xatti-harakat O'ZGARMAYDI; admin
# Film/Serial kategoriyalarini keyin ongli ravishda "classic"ga o'tkazadi.
# Model default esa "classic" — YANGI kategoriyalar (odatda kino/serial)
# uchun to'g'ri boshlanish.

from django.db import migrations, models


def existing_categories_to_reels(apps, schema_editor):
    Category = apps.get_model("drama", "Category")
    Category.objects.update(player_type="reels")


class Migration(migrations.Migration):
    dependencies = [
        ("drama", "0031_v2d_t1_tmdb_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="player_type",
            field=models.CharField(
                choices=[
                    ("classic", "Klassik (16:9 kino/serial)"),
                    ("reels", "Reels (vertikal short-drama)"),
                ],
                default="classic",
                help_text=(
                    "Reels — vertikal short-drama (fullscreen pleyer); "
                    "Klassik — 16:9 kino/serial sahifasi."
                ),
                max_length=10,
                verbose_name="Pleyer turi",
            ),
        ),
        migrations.RunPython(existing_categories_to_reels, migrations.RunPython.noop),
    ]
