# Generated by Django 6.0.7 on 2026-07-19 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0033_review_like_count_reviewreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='drama.episode'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_spoiler',
            field=models.BooleanField(default=False, verbose_name='Spoyler'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['episode', 'parent'], name='drama_revie_episode_7db1ef_idx'),
        ),
    ]
