# Generated by Django 6.0.7 on 2026-07-19 17:15

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0034_review_episode_review_is_spoiler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English'), ('ko', '한국어')], max_length=8, verbose_name='Til')),
                ('label', models.CharField(blank=True, max_length=40, verbose_name="Yorliq (bo'sh = til nomi)")),
                ('vtt_file', models.FileField(upload_to='subtitles/', validators=[core.validators.SubtitleFileValidator(max_mb=2)], verbose_name='VTT fayl')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='drama.episode')),
            ],
            options={
                'ordering': ['lang'],
                'constraints': [models.UniqueConstraint(fields=('episode', 'lang'), name='uniq_episode_subtitle_lang')],
            },
        ),
    ]
