# Generated by Django 6.0.7 on 2026-07-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0035_episodesubtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='intro_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Intro oxiri (sek)'),
        ),
        migrations.AddField(
            model_name='episode',
            name='intro_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Intro boshi (sek)'),
        ),
    ]
