# Generated by Django 6.0.7 on 2026-07-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0036_episode_intro_end_episode_intro_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='bunny_video_id',
            field=models.CharField(blank=True, help_text="Katta hajmli videoni Bunny'ga QO'LDA yuklab, video GUID'ini shu yerga qo'ying (masalan: a7332447-5828-483e-9363-218a02e6f9cc). Fayl yuklamasangiz pipeline ishlamaydi — to'g'ridan-to'g'ri shu ID ishlatiladi.", max_length=100, verbose_name='Bunny Stream Video ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='bunny_video_id',
            field=models.CharField(blank=True, help_text="Yagona filmni Bunny'ga QO'LDA yuklagan bo'lsangiz, video GUID'ini shu yerga qo'ying. Serial bo'lsa — har qismning GUID'ini “Qismlar”da kiriting.", max_length=100, verbose_name='Bunny Stream Video ID (Film)'),
        ),
    ]
