# Generated by Django 6.0.7 on 2026-07-24 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0037_alter_episode_bunny_video_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=200, verbose_name="So'rov")),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Natijalar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Qidiruv logi',
                'verbose_name_plural': 'Qidiruv analitikasi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['results_count', 'created_at'], name='drama_searc_results_12a865_idx')],
            },
        ),
    ]
