# Generated by Django 6.0.7 on 2026-08-02 19:38

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0038_searchquerylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topslider',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Bosh slayder', 'verbose_name_plural': 'Bosh slayderlar'},
        ),
        migrations.AddField(
            model_name='topslider',
            name='movie',
            field=models.ForeignKey(blank=True, help_text='Tanlansa: poster, nom va havola shu kinodan olinadi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_sliders', to='drama.movie', verbose_name='Kino'),
        ),
        migrations.AddField(
            model_name='topslider',
            name='sort_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Kichik raqam oldinda turadi.', verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='topslider',
            name='image',
            field=models.ImageField(blank=True, help_text="Kino tanlangan bo'lsa shart emas — kino posteri ishlatiladi.", upload_to='sliders/', validators=[core.validators.ImageFileValidator()], verbose_name='Slayder rasmi'),
        ),
        migrations.AlterField(
            model_name='topslider',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Slayder nomi'),
        ),
        migrations.AlterField(
            model_name='topslider',
            name='rank',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rank matni'),
        ),
    ]
