# Generated by Django 6.0.7 on 2026-07-24 11:37

import core.images
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drama', '0037_alter_episode_bunny_video_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.CharField(blank=True, help_text="Lenta/kartada va meta-description'da ishlatiladi. Bo'sh bo'lsa matn boshidan avtomatik olinadi.", max_length=300, verbose_name='Qisqa tavsif')),
                ('excerpt_uz', models.CharField(blank=True, help_text="Lenta/kartada va meta-description'da ishlatiladi. Bo'sh bo'lsa matn boshidan avtomatik olinadi.", max_length=300, null=True, verbose_name='Qisqa tavsif')),
                ('excerpt_en', models.CharField(blank=True, help_text="Lenta/kartada va meta-description'da ishlatiladi. Bo'sh bo'lsa matn boshidan avtomatik olinadi.", max_length=300, null=True, verbose_name='Qisqa tavsif')),
                ('body', models.TextField(help_text='Rich-text — admin muharriri.', verbose_name='Matn (HTML)')),
                ('body_uz', models.TextField(help_text='Rich-text — admin muharriri.', null=True, verbose_name='Matn (HTML)')),
                ('body_en', models.TextField(help_text='Rich-text — admin muharriri.', null=True, verbose_name='Matn (HTML)')),
                ('cover', models.ImageField(blank=True, upload_to='blog/covers/', verbose_name='Muqova rasmi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('scheduled', 'Rejalashtirilgan'), ('published', 'Chop etilgan')], default='draft', max_length=12, verbose_name='Holat')),
                ('publish_at', models.DateTimeField(blank=True, help_text="Rejalashtirilgan holat uchun majburiy — shu vaqtdan keyin ommaviy bo'ladi.", null=True, verbose_name='Chop etish vaqti')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('related_movies', models.ManyToManyField(blank=True, help_text="Ichki havolalar (SEO link-building) — maqola oxirida ko'rsatiladi.", related_name='blog_posts', to='drama.movie', verbose_name="Bog'liq kinolar")),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='drama.tag', verbose_name='Teglar')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-publish_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'publish_at'], name='blog_post_status_e6cf81_idx'), models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'scheduled'), _negated=True), ('publish_at__isnull', False), _connector='OR'), name='post_scheduled_requires_publish_at')],
            },
            bases=(core.images.ImageOptimizationMixin, models.Model),
        ),
    ]
