# Generated by Django 6.0.1 on 2026-03-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drama', '0014_actorgift'),
        ('users', '0006_alter_topuprequest_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.PositiveIntegerField(verbose_name="Yig'ilishi kerak bo'lgan jami Coin")),
                ('collected_amount', models.PositiveIntegerField(default=0, verbose_name="Hozirgacha yig'ildi")),
                ('min_fund_amount', models.PositiveIntegerField(default=50, verbose_name='Minimal hissa (Coin)')),
                ('post_release_price', models.PositiveIntegerField(default=100, verbose_name='Tayyor serial narxi (Coin)')),
                ('status', models.CharField(choices=[('funding', "Pul yig'ilmoqda"), ('translating', 'Tarjima jarayonida'), ('released', 'Saytga chiqdi (Tayyor)')], default='funding', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_project', to='drama.movie')),
            ],
        ),
        migrations.CreateModel(
            name='FundingContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.PositiveIntegerField()),
                ('funded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='funding.fundingproject')),
            ],
            options={
                'ordering': ['-funded_at'],
            },
        ),
    ]
