# Generated by Django 6.0.1 on 2026-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0028_movie_search_vector'),
        ('funding', '0001_initial'),
        ('users', '0018_p7_t4_hardening'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingcontributor',
            options={'ordering': ['-funded_at'], 'verbose_name': 'Funding hissasi', 'verbose_name_plural': 'Funding hissalari'},
        ),
        migrations.AlterModelOptions(
            name='fundingproject',
            options={'verbose_name': 'Funding loyihasi', 'verbose_name_plural': 'Funding loyihalari'},
        ),
        migrations.AddField(
            model_name='fundingcontributor',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Refund vaqti'),
        ),
        migrations.AlterField(
            model_name='fundingproject',
            name='status',
            field=models.CharField(choices=[('funding', "Pul yig'ilmoqda"), ('translating', 'Tarjima jarayonida'), ('released', 'Saytga chiqdi (Tayyor)'), ('canceled', 'Bekor qilindi (refund)')], default='funding', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fundingcontributor',
            index=models.Index(fields=['project', 'profile'], name='funding_contrib_proj_prof'),
        ),
        migrations.AddConstraint(
            model_name='fundingproject',
            constraint=models.CheckConstraint(condition=models.Q(('target_amount__gte', 1)), name='funding_target_amount_positive'),
        ),
    ]
