"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from google.oauth2 import service_account
from pathlib import Path
from google.cloud import storage
import mimetypes

mimetypes.add_type("font/woff2", ".woff2", True)
mimetypes.add_type("font/woff", ".woff", True)
mimetypes.add_type("font/ttf", ".ttf", True)

mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("application/javascript", ".js", True)

# GCS uchun qo'shimcha (agar django-storages ishlatayotgan bo'lsangiz)
GS_CONTENT_TYPE_LIST = ['text/css', 'application/javascript']
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iamd93l(gh6pyjr34k17ngy$py^4%)n-@zu^4&)busu8q*t21%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['drama.uz', 'www.drama.uz']


# Application definition

INSTALLED_APPS = [
    # 1. ADMIN THEME (Unfold har doim eng tepada bo'lishi shart)
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    
    # 2. TRANSLATION (Admin-dan oldin kelishi kerak)
    "modeltranslation",

    # 3. DJANGO CORE (Standart paketlar)
    'django.contrib.admin',  # Unfold-dan keyin kelishi shart!
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # Statik fayllar uchun shart
    'django.contrib.sites',        # Allauth uchun shart
    'django.contrib.sitemaps',      #google-yandex sitemap
    # 4. AUTHENTICATION (Allauth)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # 5. THIRD PARTY APPS (Qo'shimcha kutubxonalar)
    'storages',          # GCloud Storage uchun
    'crispy_forms',      # Formalar uchun
    'crispy_bootstrap5', # Crispy-ning Bootstrap 5 qismi
    'django_htmx',
    
    # 6. LOCAL APPS (Sizning shaxsiy ilovalaringiz)
    'drama',
    'users.apps.UsersConfig',
]

MIDDLEWARE = [
    'django_htmx.middleware.HtmxMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000  # 1 yil
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

APPEND_SLASH = True
SITE_ID = 1 

# Allauth uchun qo‘shimcha sozlamalar
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Email tasdiqlash (ixtiyoriy: 'optional' yoki 'none')
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # Foydalanuvchi nomi yoki email orqali kirish
# end


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 3,  # Parol uchun minimal 3 belgi
        }
    },
]
# --- Allauth & Auth ---
ACCOUNT_LOGIN_METHODS = {'username'}
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_USERNAME_MIN_LENGTH = 4

# --- Redirects ---
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'drama:movie_list'  
LOGOUT_REDIRECT_URL = 'users:login'

# --- Til va Vaqt ---
LANGUAGE_CODE = 'uz' # Asosiy til o'zbekcha
USE_I18N = True
USE_TZ = True
TIME_ZONE = 'Asia/Tashkent' # O'zbekiston vaqti

LANGUAGES = [
    ('uz', 'Oʻzbekcha'),
    ('en', 'English'),
]

# --- Email ---
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'admin@drama.uz'

# --- Crispy Forms ---
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Fayl 2.5 MB dan katta bo'lsa, uni RAM ga emas, vaqtinchalik diskka yozadi
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440 # 2.5 MB
# Umumiy yuklanadigan fayl hajmiga cheklov (masalan, 500 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000

# --- Google Cloud Storage & CDN Settings ---
# 1. Google Cloud identifikatorlari (Bularsiz tizim ishlamaydi)
GS_PROJECT_ID = 'my-drama-uz'
GS_BUCKET_NAME = 'cdn.drama.uz'
GS_QUERYSTRING_AUTH = False
GS_CUSTOM_DOMAIN = 'cdn.drama.uz'

# 2. Kalit (Service Account)
GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
    os.path.join(BASE_DIR, 'drama-key-v2.json')
)

# 3. URL-lar
STATIC_URL = f'https://{GS_CUSTOM_DOMAIN}/static/'
MEDIA_URL = f'https://{GS_CUSTOM_DOMAIN}/media/'

# Fayllar manbasi (Buni o'chirmang!)
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Bular turaversin, lekin GCS ishlayotganda ular deyarli ishlatilmaydi
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 4. Storage tizimi (Klasslarimizga yo'l ko'rsatamiz)
STORAGES = {
    "default": {
        "BACKEND": "config.custom_storage.CustomMediaStorage", 
    },
    "staticfiles": {
        "BACKEND": "config.custom_storage.CustomStaticStorage",
    },
}

UNFOLD_SETTINGS = {
    "SITE_TITLE": "Drama.uz Admin",
    "SITE_HEADER": "Drama Admin",
    "SITE_SYMBOL": "movie", # Bu yerda ikonka nomi bo'lishi kerak
    "STYLES": [
        lambda request: "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200",
    ],
    "SHOW_HISTORY": True, # O'zgarishlar tarixini ko'rsatish
    "SHOW_VIEW_ON_SITE": True, # Saytda ko'rish tugmasini chiqarish
    
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",  # Asosiy rang (binafsha - komikslar uchun mos)
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    
    "SIDEBAR": {
        "show_search": True, # Chap menyuda qidiruv paneli
        "show_all_applications": True,
    },
}