"""Blog testlari [V2G-T2] — publish workflow, ko'rinish invarianti, feed, JSON-LD, kesh."""

from __future__ import annotations

import json

import pytest
from django.urls import reverse

from blog.factories import PostFactory
from blog.models import Post
from drama.factories import MovieFactory


# ---------------------------------------------------------------------------
# Publish workflow + ko'rinish invarianti (published() manager)
# ---------------------------------------------------------------------------
@pytest.mark.django_db
def test_published_manager_visibility_invariant():
    pub = PostFactory(status=Post.Status.PUBLISHED)
    draft = PostFactory(status=Post.Status.DRAFT)
    sched_future = PostFactory.scheduled_future()
    sched_past = PostFactory.scheduled_past()

    visible = set(Post.objects.published())
    assert pub in visible
    assert sched_past in visible  # publish_at o'tgan -> ommaviy
    assert draft not in visible
    assert sched_future not in visible  # hali vaqti kelmagan


@pytest.mark.django_db
def test_scheduled_requires_publish_at_validation():
    from django.core.exceptions import ValidationError

    post = Post(title="X", status=Post.Status.SCHEDULED, publish_at=None)
    with pytest.raises(ValidationError):
        post.clean()


@pytest.mark.django_db
def test_published_without_publish_at_gets_now():
    post = PostFactory(status=Post.Status.PUBLISHED, publish_at=None)
    assert post.publish_at is not None


@pytest.mark.django_db
def test_slug_autogenerated_and_unique():
    a = PostFactory(title="Bir xil sarlavha", slug="")
    b = PostFactory(title="Bir xil sarlavha", slug="")
    assert a.slug and b.slug
    assert a.slug != b.slug


# ---------------------------------------------------------------------------
# List + detail ko'rinishi
# ---------------------------------------------------------------------------
@pytest.mark.django_db
def test_list_shows_only_published(client):
    PostFactory(status=Post.Status.PUBLISHED, title="Ommaviy maqola")
    PostFactory(status=Post.Status.DRAFT, title="Qoralama maqola")
    resp = client.get(reverse("blog:post_list"))
    assert resp.status_code == 200
    body = resp.content.decode()
    assert "Ommaviy maqola" in body
    assert "Qoralama maqola" not in body


@pytest.mark.django_db
def test_detail_published_ok(client):
    post = PostFactory(status=Post.Status.PUBLISHED)
    resp = client.get(post.get_absolute_url())
    assert resp.status_code == 200
    assert post.title in resp.content.decode()


@pytest.mark.django_db
def test_detail_draft_is_404(client):
    draft = PostFactory(status=Post.Status.DRAFT)
    resp = client.get(reverse("blog:post_detail", kwargs={"slug": draft.slug}))
    assert resp.status_code == 404


@pytest.mark.django_db
def test_detail_scheduled_future_is_404(client):
    post = PostFactory.scheduled_future()
    resp = client.get(reverse("blog:post_detail", kwargs={"slug": post.slug}))
    assert resp.status_code == 404


@pytest.mark.django_db
def test_body_rendered_as_html(client):
    post = PostFactory(body="<p>Salom <strong>dunyo</strong></p>")
    resp = client.get(post.get_absolute_url())
    # |safe -> teglar escape qilinmaydi
    assert "<strong>dunyo</strong>" in resp.content.decode()


@pytest.mark.django_db
def test_related_movies_only_published(client):
    post = PostFactory()
    pub_movie = MovieFactory()
    draft_movie = MovieFactory(status="draft")
    post.related_movies.add(pub_movie, draft_movie)
    resp = client.get(post.get_absolute_url())
    body = resp.content.decode()
    assert pub_movie.title in body
    assert draft_movie.title not in body


# ---------------------------------------------------------------------------
# JSON-LD Article
# ---------------------------------------------------------------------------
@pytest.mark.django_db
def test_article_jsonld_valid(client):
    post = PostFactory(status=Post.Status.PUBLISHED, excerpt="Qisqa tavsif")
    resp = client.get(post.get_absolute_url())
    body = resp.content.decode()
    # Sahifada BIR NECHA ld+json bor (base.html WebSite + maqola grafi) — @graph'lisini topamiz
    import re

    blocks = re.findall(r'type="application/ld\+json">(.*?)</script>', body, re.S)
    graph = None
    for raw in blocks:
        parsed = json.loads(raw)
        if isinstance(parsed, dict) and "@graph" in parsed:
            graph = parsed["@graph"]
            break
    assert graph is not None, "Article @graph topilmadi"
    types = {node["@type"] for node in graph}
    assert "Article" in types
    assert "BreadcrumbList" in types
    article = next(n for n in graph if n["@type"] == "Article")
    assert article["headline"] == post.title
    assert article["description"] == "Qisqa tavsif"
    assert "datePublished" in article


# ---------------------------------------------------------------------------
# RSS feed
# ---------------------------------------------------------------------------
@pytest.mark.django_db
def test_rss_feed_lists_published_only(client):
    PostFactory(status=Post.Status.PUBLISHED, title="Feed ommaviy")
    PostFactory(status=Post.Status.DRAFT, title="Feed qoralama")
    resp = client.get(reverse("blog:rss"))
    assert resp.status_code == 200
    assert resp["Content-Type"].startswith("application/rss+xml")
    body = resp.content.decode()
    assert "Feed ommaviy" in body
    assert "Feed qoralama" not in body
    assert "<rss" in body and "<channel>" in body


# ---------------------------------------------------------------------------
# Sitemap
# ---------------------------------------------------------------------------
@pytest.mark.django_db
def test_sitemap_includes_published_post_with_alternates(client):
    PostFactory(status=Post.Status.PUBLISHED, slug="sitemap-post")
    PostFactory(status=Post.Status.DRAFT, slug="sitemap-draft")
    body = client.get("/sitemap.xml").content.decode()
    assert "/yangiliklar/sitemap-post/" in body
    assert "sitemap-draft" not in body
    # i18n alternates (V2G-T1 mixin)
    assert "/en/yangiliklar/sitemap-post/" in body


# ---------------------------------------------------------------------------
# Kesh — versiyalangan kalit + bump
# ---------------------------------------------------------------------------
@pytest.mark.django_db
def test_blog_cache_bumps_on_post_save():
    from blog.cache import blog_version

    v1 = blog_version()
    PostFactory()  # post_save signal -> bump
    v2 = blog_version()
    assert v2 > v1


@pytest.mark.django_db
def test_homepage_widget_cached_and_published_only():
    from blog.views import blog_widget_posts

    pub = PostFactory(status=Post.Status.PUBLISHED)
    PostFactory(status=Post.Status.DRAFT)
    posts = blog_widget_posts(4)
    assert pub in posts
    assert all(p.status != Post.Status.DRAFT for p in posts)


@pytest.mark.django_db
def test_homepage_shows_yangiliklar_block(client):
    PostFactory(status=Post.Status.PUBLISHED, title="Bosh sahifa yangiligi")
    resp = client.get("/")
    assert resp.status_code == 200
    assert "Bosh sahifa yangiligi" in resp.content.decode()
